version: '3.8'
volumes:
  postgres-data-dev:
    driver: local

services:
  postgres-db:
    image: postgres
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: nestjs-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH=${JWT_REFRESH}
    depends_on:
      - postgres-db
